export const LOADING_ALERTAS_MAXIMAS = "LOADING_ALERTAS_MAXIMAS";
export const GET_ALERTAS_MAXIMAS = "GET_ALERTAS_MAXIMAS";
export const ALERTAS_MAXIMAS_FAIL = "ALERTAS_MAXIMAS_FAIL";
export const LOADING_ALERTA_MAXIMA_BY_ID = "LOADING_ALERTA_MAXIMA_BY_ID";
export const GET_ALERTA_MAXIMA_BY_ID = "GET_ALERTA_MAXIMA_BY_ID";
