export const BODEGA_PRINCIPAL = "001"
//export const BODEGA_PRINCIPAL = "080"
export const ADMIN_SECUNDARIA = "002"

export const COSTO_RECARGA = 50.00

export const ROLES = {
    SUPERVISOR: "Supervisor",
    ADMINISTRADOR: "Administrador",
    ENCARGADO: "Encargado"
}

export const TIPO_PRODUCTO = {
    SIM_PORTABILIDAD: "SIM portabilidad",
    SIM_DISTRIBUCION: "SIM distribución",
    CELULAR: "Celular",
    NO_SERIALIZADOS: "No serializados"
}

export const TIPO_METODO_PAGO = {
    EFECTIVO: "Efectivo",
    TARJETA_CREDITO: "Tarjeta de Crédito"
}

export const TIPO_LOCAL = {
    BODEGA_PRINCIPAL: "Oficina Principal",
    TIENDA: "Tienda",
    PUNTO_ESTACIONARIO:"Punto Estacionario"
}

export const TIPO_VENTA = {
    "KREDIYA": "Krediya",
    "DURSAN": "Dursan",
    "CUOTA": "Cuota Krediya",
    "OI" : "OI"
}

export const PERMISOS = {
    ACCEDER_DASHBOARD_ESPECIFICO: "ACCEDER_DASHBOARD_ESPECIFICO",
    ACCEDER_DASHBOARD_GENERAL: "ACCEDER_DASHBOARD_GENERAL",
    ACCEDER_MODULO_INVENTARIO: "ACCEDER_MODULO_INVENTARIO",
    ACCEDER_ALERTAS_GENERAL: "ACCEDER_ALERTAS_GENERAL",
    ACCEDER_ALERTAS_ESPECIFICO: "ACCEDER_ALERTAS_ESPECIFICO",
    ACCEDER_INVENTARIO_GENERAL: "ACCEDER_INVENTARIO_GENERAL",
    ACCEDER_INVENTARIO_BODEGA: "ACCEDER_INVENTARIO_BODEGA",
    ACCEDER_INVENTARIO_POR_TIENDA_ESPECIFICO: "ACCEDER_INVENTARIO_POR_TIENDA_ESPECIFICO",
    ACCEDER_INVENTARIO_POR_TIENDA_GENERAL: "ACCEDER_INVENTARIO_POR_TIENDA_GENERAL",
    ACCEDER_INVENTARIO_SUPERVISORES_GENERAL: "ACCEDER_INVENTARIO_SUPERVISORES_GENERAL",
    ACCEDER_INVENTARIO_SUPERVISORES_ESPECIFICO: "ACCEDER_INVENTARIO_SUPERVISORES_ESPECIFICO",
    ACCEDER_INVENTARIO_PUNTOS_ESTACIONARIOS: "ACCEDER_INVENTARIO_PUNTOS_ESTACIONARIOS",
    ACCEDER_VER_EXISTENCIAS: "ACCEDER_VER_EXISTENCIAS",
    ACCEDER_AGREGAR_A_STOCK: "ACCEDER_AGREGAR_A_STOCK",
    ACCEDER_ASIGNAR_ENTRE_TIENDAS: "ACCEDER_ASIGNAR_ENTRE_TIENDAS",
    ACCEDER_ASIGNAR_A_SUPERVISORES: "ACCEDER_ASIGNAR_A_SUPERVISORES",
    ACCEDER_ASIGNAR: "ACCEDER_ASIGNAR",
    ACCEDER_HISTORIAL_GENERAL: "ACCEDER_HISTORIAL_GENERAL",
    ACCEDER_HISTORIAL_ESPECIFICO: "ACCEDER_HISTORIAL_ESPECIFICO",
    ACCEDER_HISTORIAL_SIMS_GENERAL_SUPERVISOR: "ACCEDER_HISTORIAL_SIMS_GENERAL_SUPERVISOR",
    ACCEDER_HISTORIAL_SIMS_ESPECIFICO: "ACCEDER_HISTORIAL_SIMS_ESPECIFICO",
    ACCEDER_HISTORIAL_MOVIMIENTOS: "ACCEDER_HISTORIAL_MOVIMIENTOS",
    ACCEDER_MODULO_FACTURACION: "ACCEDER_MODULO_FACTURACION",
    ACCEDER_VENTA_DURSAN: "ACCEDER_VENTA_DURSAN",
    ACCEDER_VENTA_KREDIYA: "ACCEDER_VENTA_KREDIYA",
    ACCEDER_GENERAR_VENTA: "ACCEDER_GENERAR_VENTA",
    ACCEDER_PAGO_CUOTA_KREDIYA: "ACCEDER_PAGO_CUOTA_KREDIYA",
    ACCEDER_HISTORIAL_VENTAS_DURSAN_GENERAL: "ACCEDER_HISTORIAL_VENTAS_DURSAN_GENERAL",
    ACCEDER_HISTORIAL_VENTAS_DURSAN_ESPECIFICO: "ACCEDER_HISTORIAL_VENTAS_DURSAN_ESPECIFICO",
    ACCEDER_HISTORIAL_VENTAS_KREDIYA_GENERAL: "ACCEDER_HISTORIAL_VENTAS_KREDIYA_GENERAL",
    ACCEDER_HISTORIAL_VENTAS_KREDIYA_ESPECIFICO: "ACCEDER_HISTORIAL_VENTAS_KREDIYA_ESPECIFICO",
    ACCEDER_HISTORIAL_CUOTAS_KREDIYA_GENERAL: "ACCEDER_HISTORIAL_CUOTAS_KREDIYA_GENERAL",
    ACCEDER_HISTORIAL_CUOTAS_KREDIYA_ESPECIFICO: "ACCEDER_HISTORIAL_CUOTAS_KREDIYA_ESPECIFICO",
    ACCEDER_HISTORIAL_VENTAS: "ACCEDER_HISTORIAL_VENTAS",
    ACCEDER_ARQUEO: "ACCEDER_ARQUEO",
    ACCEDER_HISTORIAL_ARQUEO_GENERAL: "ACCEDER_HISTORIAL_ARQUEO_GENERAL",
    ACCEDER_HISTORIAL_ARQUEO_ESPECIFICO: "ACCEDER_HISTORIAL_ARQUEO_ESPECIFICO",
    ACCEDER_MANTENIMIENTO: "ACCEDER_MANTENIMIENTO",
    ACCEDER_MTN_TIPO_PRODUCTO: "ACCEDER_MTN_TIPO_PRODUCTO",
    ACCEDER_MTN_TIPO_LOCAL: "ACCEDER_MTN_TIPO_LOCAL",
    ACCEDER_MTN_CLIENTES: "ACCEDER_MTN_CLIENTES",
    ACCEDER_MTN_METODOS_PAGOS: "ACCEDER_MTN_METODOS_PAGOS",
    ACCEDER_MTN_ROL : "ACCEDER_MTN_ROL",
    ACCEDER_MTN_EMPRESA: "ACCEDER_MTN_EMPRESA",
    ACCEDER_MTN_DENOMINACION: "ACCEDER_MTN_DENOMINACION",
    ACCEDER_MTN_PRODUCTO:"ACCEDER_MTN_PRODUCTO",
    ACCEDER_MTN_EMPLEADO: "ACCEDER_MTN_EMPLEADO",
    ACCEDER_MTN_LOCAL: "ACCEDER_MTN_LOCAL",
    ACCEDER_MTN_META: "ACCEDER_MTN_META",
    ACCEDER_MTN_USUARIO: "ACCEDER_MTN_USUARIO",
    ACCEDER_MTN_RANGOS_FACTURAS:"ACCEDER_MTN_RANGOS_FACTURAS",
    PERMISO_EDITAR: "PERMISO_EDITAR",
    PERMISO_ELIMINAR: "PERMISO_ELIMINAR"
    
}

