export const LOADING_HISTORIAL_MOVIMIENTO = "LOADING_HISTORIAL_MOVIMIENTO";
export const GET_HISTORIAL_MOVIMIENTO = "GET_HISTORIAL_MOVIMIENTO";
export const HISTORIAL_MOVIMIENTO_FAIL = "HISTORIAL_MOVIMIENTO_FAIL";

export const LOADING_HISTORIAL_MOVIMIENTO_BY_ID = "LOADING_HISTORIAL_MOVIMIENTO_BY_ID";
export const GET_HISTORIAL_MOVIMIENTO_BY_ID = "GET_HISTORIAL_MOVIMIENTO_BY_ID";
export const HISTORIAL_MOVIMIENTO_BY_ID_FAIL = "HISTORIAL_MOVIMIENTO_BY_ID_FAIL";