export const LOADING_USUARIO = "LOADING_USUARIO";
export const SAVE_LOADING_USUARIO = "SAVE_LOADING_USUARIO";
export const GET_USUARIO = "GET_USUARIO";
export const FORM_FAIL = "FORM_FAIL";
export const USUARIO_FAIL = "USUARIO_FAIL";
export const LOADING_USUARIO_BY_ID = "LOADING_USUARIO_BY_ID";
export const GET_USUARIO_BY_ID = "GET_USUARIO_BY_ID";