export const LOADING_EMPRESA = "LOADING_EMPRESA";
export const SAVE_LOADING_EMPRESA = "SAVE_LOADING_EMPRESA";
export const GET_EMPRESA = "GET_EMPRESA";
export const FORM_FAIL = "FORM_FAIL";
export const EMPRESA_FAIL = "EMPRESA_FAIL";
export const LOADING_EMPRESA_BY_ID = "LOADING_EMPRESA_BY_ID";
export const GET_EMPRESA_BY_ID = "GET_EMPRESA_BY_ID";