export const LOADING_DENOMINACION = "LOADING_DENOMINACION";
export const SAVE_LOADING_DENOMINACION = "SAVE_LOADING_DENOMINACION";
export const GET_DENOMINACION = "GET_DENOMINACION";
export const FORM_FAIL = "FORM_FAIL";
export const DENOMINACION_FAIL = "DENOMINACION_FAIL";
export const LOADING_DENOMINACION_BY_ID = "LOADING_DENOMINACION_BY_ID";
export const GET_DENOMINACION_BY_ID = "GET_DENOMINACION_BY_ID";