export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS"
export const LOGOUT = "LOGOUT"
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_REQUEST = "LOGIN_REQUEST"
