export const LOADING_TIPO_LOCAL = "LOADING_TIPO_LOCAL";
export const SAVE_LOADING_TIPO_LOCAL = "SAVE_LOADING_TIPO_LOCAL";
export const GET_TIPO_LOCAL = "GET_TIPO_LOCAL";
export const FORM_FAIL = "FORM_FAIL";
export const TIPO_LOCAL_FAIL = "TIPO_LOCAL_FAIL";
export const LOADING_TIPO_LOCAL_BY_ID = "LOADING_TIPO_LOCAL_BY_ID";
export const GET_TIPO_LOCAL_BY_ID = "GET_TIPO_LOCAL_BY_ID";
