export const LOADING_CLIENTE = "LOADING_CLIENTE";
export const SAVE_LOADING_CLIENTE = "SAVE_LOADING_CLIENTE";
export const GET_CLIENTE = "GET_CLIENTE";
export const FORM_FAIL = "FORM_FAIL";
export const CLIENTE_FAIL = "CLIENTE_FAIL";
export const LOADING_CLIENTE_BY_ID = "LOADING_CLIENTE_BY_ID";
export const GET_CLIENTE_BY_ID = "GET_CLIENTE_BY_ID";