export const LOADING_DETALLE_VENTA = "LOADING_DETALLE_VENTA";
export const GET_DETALLE_VENTA = "GET_DETALLE_VENTA";
export const DETALLE_VENTA_FAIL = "DETALLE_VENTA_FAIL";
export const FORM_FAIL = "FORM_FAIL";