export const LOADING_RANGO_FACTURA = "LOADING_RANGO_FACTURA";
export const SAVE_LOADING_RANGO_FACTURA = "SAVE_LOADING_RANGO_FACTURA";
export const GET_RANGO_FACTURA = "GET_RANGO_FACTURA";
export const FORM_FAIL = "FORM_FAIL";
export const RANGO_FACTURA_FAIL = "RANGO_FACTURA_FAIL";
export const LOADING_RANGO_FACTURA_BY_ID = "LOADING_RANGO_FACTURA_BY_ID";
export const GET_RANGO_FACTURA_BY_ID = "GET_RANGO_FACTURA_BY_ID";