export const LOADING_METODO_PAGO = "LOADING_METODO_PAGO";
export const SAVE_LOADING_METODO_PAGO = "SAVE_LOADING_METODO_PAGO";
export const GET_METODO_PAGO = "GET_METODO_PAGO";
export const FORM_FAIL = "FORM_FAIL";
export const METODO_PAGO_FAIL = "METODO_PAGO_FAIL";
export const LOADING_METODO_PAGO_BY_ID = "LOADING_METODO_PAGO_BY_ID";
export const GET_METODO_PAGO_BY_ID = "GET_METODO_PAGO_BY_ID";