export const LOADING_PRODUCTO = "LOADING_PRODUCTO";
export const SAVE_LOADING_PRODUCTO = "SAVE_LOADING_PRODUCTO";
export const GET_PRODUCTO = "GET_PRODUCTO";
export const FORM_FAIL = "FORM_FAIL";
export const PRODUCTO_FAIL = "PRODUCTO_FAIL";
export const LOADING_PRODUCTO_BY_ID = "LOADING_PRODUCTO_BY_ID";
export const GET_PRODUCTO_BY_ID = "GET_PRODUCTO_BY_ID";