export const LOADING_PERMISOS = "LOADING_PERMISOS";
export const SAVE_LOADING_PERMISOS = "SAVE_LOADING_PERMISOS";
export const GET_PERMISOS = "GET_PERMISOS";
export const FORM_FAIL = "FORM_FAIL";
export const PERMISOS_FAIL = "PERMISOS_TYPE_FAIL";
export const PERMISOS_BY_ID_FAIL = "PERMISOS_BY_ID_FAIL";
export const LOADING_PERMISOS_BY_ID = "LOADING_PERMISOS_BY_ID";
export const GET_PERMISOS_BY_ID = "GET_PERMISOS_BY_ID";