export const LOADING_ARQUEO = "LOADING_ARQUEO";
export const SAVE_LOADING_ARQUEO = "SAVE_LOADING_ARQUEO";
export const GET_ARQUEO = "GET_ARQUEO";
export const FORM_FAIL = "FORM_FAIL";
export const ARQUEO_FAIL = "ARQUEO_FAIL";
export const ARQUEO_BY_ID_FAIL = "ARQUEO_BY_ID_FAIL";
export const LOADING_ARQUEO_BY_ID = "LOADING_ARQUEO_BY_ID";
export const GET_ARQUEO_BY_ID = "GET_ARQUEO_BY_ID";
export const GET_RESUMEN_METODO_PAGO = "GET_RESUMEN_METODO_PAGO";
export const LOADING_RESUMEN_METODO_PAGO = "LOADING_RESUMEN_METODO_PAGO";
export const RESUMEN_METODO_PAGO_FAIL = "RESUMEN_METODO_PAGO_FAIL";


export const GET_DENOMINACION = "GET_DENOMINACION";
export const LOADING_DENOMINACION = "LOADING_DENOMINACION";
export const DENOMINACION_FAIL = "RESUMEN_METODO_PAGO_FAIL";
