export const LOADING_PRODUCT_TYPE = "LOADING_PRODUCT_TYPE";
export const SAVE_LOADING_PRODUCT_TYPE = "SAVE_LOADING_PRODUCT_TYPE";
export const GET_PRODUCT_TYPE = "GET_PRODUCT_TYPE";
export const FORM_FAIL = "FORM_FAIL";
export const PRODUCT_TYPE_FAIL = "PRODUCT_TYPE_FAIL";
export const LOADING_PRODUCT_TYPE_BY_ID = "LOADING_PRODUCT_TYPE_BY_ID";
export const GET_PRODUCT_TYPE_BY_ID = "GET_PRODUCT_TYPE_BY_ID";