export const LOADING_EMPLEADO = "LOADING_EMPLEADO";
export const SAVE_LOADING_EMPLEADO = "SAVE_LOADING_EMPLEADO";
export const GET_EMPLEADO = "GET_EMPLEADO";
export const FORM_FAIL = "FORM_FAIL";
export const EMPLEADO_FAIL = "EMPLEADO_FAIL";
export const LOADING_EMPLEADO_BY_ID = "LOADING_EMPLEADO_BY_ID";
export const GET_EMPLEADO_BY_ID = "GET_EMPLEADO_BY_ID";