export const LOADING_CUMPLIMIENTO_METAS = "LOADING_CUMPLIMIENTO_METAS";
export const GET_CUMPLIMIENTO_METAS = "GET_CUMPLIMIENTO_METAS";
export const CUMPLIMIENTO_METAS_FAIL = "CUMPLIMIENTO_METAS_FAIL";

export const LOADING_VENTAS_MENSUALES = "LOADING_VENTAS_MENSUALES";
export const GET_VENTAS_MENSUALES = "GET_VENTAS_MENSUALES";
export const VENTAS_MENSUALES_FAIL = "VENTAS_MENSUALES_FAIL";

export const LOADING_TOP_PRODUCTOS = "LOADING_TOP_PRODUCTOS";
export const GET_TOP_PRODUCTOS = "GET_TOP_PRODUCTOS";
export const TOP_PRODUCTOS_FAIL = "TOP_PRODUCTOS_FAIL";

export const LOADING_TOP_LOCALES = "LOADING_TOP_LOCALES";
export const GET_TOP_LOCALES = "GET_TOP_LOCALES";
export const TOP_LOCALES_FAIL = "TOP_LOCALES_FAIL";


export const LOADING_KPIS = "LOADING_KPIS";
export const GET_KPIS = "GET_KPIS";
export const KPIS_FAIL = "KPIS_FAIL";
